# Generated by Django 3.1.2 on 2020-12-01 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20201201_1229'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='passWord',
        ),
    ]
