# Generated by Django 3.1.2 on 2020-12-02 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicKey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPublicKey', models.CharField(max_length=200)),
                ('publicKey', models.CharField(max_length=200)),
            ],
        ),
    ]
