# Generated by Django 3.1.2 on 2020-12-02 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_publickey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publickey',
            name='publicKey',
        ),
        migrations.RemoveField(
            model_name='user',
            name='publicKey',
        ),
        migrations.AddField(
            model_name='publickey',
            name='publicKeyE',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='publickey',
            name='publicKeyN',
            field=models.CharField(default='', max_length=200),
        ),
    ]
